# Generated by Django 6.0.3 on 2026-04-01 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0004_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnaliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luna', models.PositiveSmallIntegerField(choices=[(1, 'Ianuarie'), (2, 'Februarie'), (3, 'Martie'), (4, 'Aprilie'), (5, 'Mai'), (6, 'Iunie'), (7, 'Iulie'), (8, 'August'), (9, 'Septembrie'), (10, 'Octombrie'), (11, 'Noiembrie'), (12, 'Decembrie')])),
                ('an', models.PositiveSmallIntegerField()),
                ('continut_analiza', models.TextField()),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analiză AI',
                'verbose_name_plural': 'Analize AI',
                'ordering': ['-an', '-luna', '-creat_la'],
                'constraints': [models.UniqueConstraint(fields=('utilizator', 'luna', 'an'), name='unique_ai_analysis_per_month_year')],
            },
        ),
    ]
