# Generated by Django 6.0.3 on 2026-04-02 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0005_aianaliza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_gospodarie', models.CharField(choices=[('single', 'Single'), ('cuplu', 'Cuplu'), ('familie_copii', 'Familie cu copii'), ('colegi_casa', 'Colegi de casă')], default='single', max_length=20)),
                ('nr_persoane', models.IntegerField(default=1)),
                ('are_copii', models.BooleanField(default=False)),
                ('venit_lunar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('obiectiv', models.CharField(choices=[('economisire', 'Economisire'), ('stabilitate', 'Stabilitate'), ('investitii', 'Investiții'), ('iesire_datorii', 'Ieșire din datorii')], default='stabilitate', max_length=20)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilizator',
                'verbose_name_plural': 'Profiluri utilizatori',
            },
        ),
    ]
