# Generated by Django 6.0.3 on 2026-04-03 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('depasire_iminenta', 'Depășire iminentă'), ('ritm_alert', 'Ritm alert'), ('economie_posibila', 'Economie posibilă'), ('recurenta_detectata', 'Recurență detectată')], max_length=30)),
                ('mesaj', models.TextField()),
                ('suma_implicata', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('zile_ramase', models.IntegerField(blank=True, null=True)),
                ('actiune_recomandata', models.TextField()),
                ('citita', models.BooleanField(default=False)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spndix.categorie')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alertă forecast',
                'verbose_name_plural': 'Alerte forecast',
                'ordering': ['citita', '-creat_la'],
            },
        ),
    ]
