# Generated by Django 6.0.3 on 2026-04-03 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0007_forecastalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('suma_tinta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('suma_curenta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_tinta', models.DateField(blank=True, null=True)),
                ('culoare', models.CharField(default='#6366f1', max_length=7)),
                ('icon', models.CharField(default='bi-piggy-bank', max_length=50)),
                ('activ', models.BooleanField(default=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings goal',
                'verbose_name_plural': 'Savings goals',
                'ordering': ['-activ', 'data_tinta', '-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('data', models.DateField()),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributii', to='spndix.savingsgoal')),
            ],
            options={
                'verbose_name': 'Contribuție goal',
                'verbose_name_plural': 'Contribuții goals',
                'ordering': ['-data', '-creat_la'],
            },
        ),
    ]
