# Generated by Django 6.0.3 on 2026-04-06 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0008_savingsgoal_goalcontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastalert',
            name='tip',
            field=models.CharField(choices=[('depasire_iminenta', 'Depășire iminentă'), ('ritm_alert', 'Ritm alert'), ('economie_posibila', 'Economie posibilă'), ('recurenta_detectata', 'Recurență detectată'), ('abonament_iminent', 'Abonament iminent')], max_length=30),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('suma_estimata', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frecventa', models.CharField(choices=[('lunar', 'Lunar'), ('anual', 'Anual'), ('saptamanal', 'Săptămânal')], default='lunar', max_length=20)),
                ('ziua_lunii', models.IntegerField(blank=True, null=True)),
                ('activ', models.BooleanField(default=True)),
                ('detectat_automat', models.BooleanField(default=False)),
                ('ultima_plata', models.DateField(blank=True, null=True)),
                ('urmatoarea_plata', models.DateField(blank=True, null=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spndix.categorie')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonament',
                'verbose_name_plural': 'Abonamente',
                'ordering': ['-activ', 'urmatoarea_plata', 'nume'],
            },
        ),
    ]
