# Generated by Django 6.0.3 on 2026-04-06 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0009_alter_forecastalert_tip_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=20)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log export',
                'verbose_name_plural': 'Loguri export',
                'ordering': ['-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='ScanareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanare_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log scanare',
                'verbose_name_plural': 'Loguri scanare',
                'ordering': ['-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('family', 'Family')], default='free', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('activ', models.BooleanField(default=True)),
                ('data_expirare', models.DateField(blank=True, null=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userplan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan utilizator',
                'verbose_name_plural': 'Planuri utilizatori',
            },
        ),
    ]
