# Generated by Django 6.0.3 on 2026-04-07 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spndix', '0010_exportlog_scanarelog_userplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastalert',
            name='tip',
            field=models.CharField(choices=[('depasire_iminenta', 'Depășire iminentă'), ('ritm_alert', 'Ritm alert'), ('economie_posibila', 'Economie posibilă'), ('recurenta_detectata', 'Recurență detectată'), ('abonament_iminent', 'Abonament iminent'), ('abonament_scumpit', 'Abonament scumpit'), ('sugestie_anulare', 'Sugestie anulare')], max_length=30),
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=120)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gospodărie',
                'verbose_name_plural': 'Gospodării',
                'ordering': ['-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField(default=django.utils.timezone.localdate)),
                ('data_tinta', models.DateField(blank=True, null=True)),
                ('first_win_obtinut', models.BooleanField(default=False)),
                ('first_win_la', models.DateTimeField(blank=True, null=True)),
                ('ascuns', models.BooleanField(default=False)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('actualizat_la', models.DateTimeField(auto_now=True)),
                ('utilizator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_journey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboarding',
            },
        ),
        migrations.CreateModel(
            name='SmartAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=220)),
                ('descriere', models.TextField(blank=True)),
                ('tip', models.CharField(choices=[('buget', 'Buget'), ('abonament', 'Abonament'), ('economii', 'Economii'), ('onboarding', 'Onboarding')], default='buget', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('done', 'Finalizat'), ('dismissed', 'Ignorat')], default='pending', max_length=20)),
                ('impact_estimat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_scadenta', models.DateField(blank=True, null=True)),
                ('completata_la', models.DateTimeField(blank=True, null=True)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_action', to='spndix.forecastalert')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Smart action',
                'verbose_name_plural': 'Smart actions',
                'ordering': ['status', 'data_scadenta', '-creat_la'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('owner', 'Owner'), ('adult', 'Adult'), ('copil', 'Copil')], default='adult', max_length=20)),
                ('responsabilitate', models.CharField(blank=True, max_length=200)),
                ('activ', models.BooleanField(default=True)),
                ('adaugat_la', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membri', to='spndix.household')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membru gospodărie',
                'verbose_name_plural': 'Membri gospodărie',
                'ordering': ['household__nume', 'utilizator__username'],
                'constraints': [models.UniqueConstraint(fields=('household', 'utilizator'), name='unique_household_member')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazin', models.CharField(max_length=160)),
                ('data_bon', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nr_produse', models.PositiveIntegerField(default=0)),
                ('pret_mediu_produs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produse_json', models.JSONField(blank=True, default=list)),
                ('creat_la', models.DateTimeField(auto_now_add=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt insight',
                'verbose_name_plural': 'Receipt insights',
                'ordering': ['-data_bon', '-creat_la'],
                'indexes': [models.Index(fields=['utilizator', 'data_bon'], name='spndix_rece_utiliza_6bfef9_idx')],
            },
        ),
    ]
